### ISSUE TITLE
Se produjo una excepción en el controlador: SQLSTATE [HY000] [1045] Acceso denegado para el usuario 'db_user' @ 'localhost' (usando la contraseña: YES)

### ISSUE THREAD

**Issue by Jenderz** [giorgiopagnoni/symfony4-user#1]
**## I liked this initiative and I would like to use it, could you tell me the installation steps together with the database. Happy day**

**Comment by giorgiopagnoni** [comment]
Set your environment variables in `.env` (use `.env.dist` as a template). You can set DATABASE_URL to `mysql://root:@127.0.0.1:3306/symfony4user` for example on your dev machine. Then run `php bin/console doctrine:database:create` and `php app/console doctrine:migrations:migrate`. You'll also need to set RECAPTCHA_KEY and RECAPTCHA_SECRET.

**Comment by Jenderz** [comment]
![2018-01-25-144159_1024x600_scrot](https://user-images.githubusercontent.com/33388647/35405966-04f85250-01de-11e8-89f0-ddbbc94dd218.png)

![2018-01-25-144517_1024x600_scrot](https://user-images.githubusercontent.com/33388647/35406109-697d8114-01de-11e8-8066-2054bdb631ee.png)

## **friend, I'm a novice in the php framework. And I'm starting Symfony, could you give me a little more detailed guidance?**

**Comment by Jenderz** [comment]
![2018-01-25-154510_1024x600_scrot](https://user-images.githubusercontent.com/33388647/35408910-10020b38-01e7-11e8-8ee6-1fc60ec7f2bf.png)

## 
_Perfect friend, thank you, now I have this problem, I think it is that I must have a domain to validate the key. What do you think?_

**Comment by giorgiopagnoni** [comment]
Google recaptcha, get the the keys and set them in the .env file. But I really believe you should just follow a free course like this one https://knpuniversity.com/tracks/symfony, also Symfony 3. They have nice videos and their pace is slow. This is where I learned everything I know about Symfony, for free.

**Comment by Jenderz** [comment]
And what I asked was done, I got keys through Google reCAPTCHA, and it does not work. Thank you, friend, in that I am. Learning, greetings

**Comment by giorgiopagnoni** [comment]
You can set the domain in the google reCaptcha page.

**Comment by Jenderz** [comment]
_I'm from a local server, you can tell me how I can use it by deactivating Recapcha temporarily. Thanks, you can close!_

**Comment by giorgiopagnoni** [comment]
Remove the captcha from the templates in register and request-password-reset, and remove the try-catch block with the catptcha validator in UserController.
